export enum AIInteractionType {
	GENERAL = 'GENERAL',
	EMAIL_GENERATION = 'EMAIL_GENERATION',
	WEB_SEARCH = 'WEB_SEARCH',
	SENTIMENT_ANALYSIS = 'SENTIMENT_ANALYSIS',
	MEETING_ANALYSIS = 'MEETING_ANALYSIS'
}
